version: '2'

services:

  landing_page:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=cogs.floop.org.uk
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=cogs.floop.org.uk
      - LETSENCRYPT_EMAIL=alex@floop.org.uk
    networks:
      - cloudfluff_proxy
      - default

networks:
  cloudfluff_proxy:
    external: true